import Link from 'next/link'
import AppShell from '@/components/AppShell'
import ProgressBar from '@/components/ProgressBar'
import {requireMember,roleLabels} from '@/lib/auth/require-member'
import {localDateISO,formatDate} from '@/lib/date'
import {getPerformanceData} from '@/lib/performance'

type SP=Promise<{range?:string}>
function bounds(range:string,today:string,year:any){const [y,m,d]=today.split('-').map(Number);if(range==='day')return[today,today];if(range==='year'&&year)return today<year.starts_on?[today,today]:[year.starts_on,today>year.ends_on?year.ends_on:today];if(range==='week'){const dt=new Date(Date.UTC(y,m-1,d));const dow=dt.getUTCDay()||7;dt.setUTCDate(dt.getUTCDate()-(dow-1));return[dt.toISOString().slice(0,10),today]}return[`${today.slice(0,7)}-01`,today]}

export default async function StatisticsPage({searchParams}:{searchParams:SP}){
  const {supabase,profile,isManager,canViewAll}=await requireMember();const params=await searchParams;const range=['day','week','month','year'].includes(params.range??'')?params.range!:'month';const today=localDateISO();const {data:year}=await supabase.from('school_years').select('id,name,starts_on,ends_on').eq('is_active',true).maybeSingle();const [from,to]=bounds(range,today,year);const {rows,department}=await getPerformanceData({supabase,profileId:profile.id,canViewAll,schoolYearId:year?.id,from,to})
  return <AppShell name={profile.full_name||'Collègue'} roleLabel={roleLabels[profile.role]} active="/statistics" isManager={isManager}><header className="page-header"><div><p className="eyebrow">Pilotage</p><h1>Statistiques</h1><p className="muted">Indicateurs calculés automatiquement à partir des séances et de la progression.</p></div></header><div className="range-tabs">{[['day','Jour'],['week','Semaine'],['month','Mois'],['year','Année']].map(([v,l])=><Link className={range===v?'active':''} href={`/statistics?range=${v}`} key={v}>{l}</Link>)}</div><div className="summary-strip"><strong>{formatDate(from)} → {formatDate(to)}</strong><span>{year?.name?`Année ${year.name}`:'Aucune année active'}</span></div>
  {department&&<><section className="metric-grid compact-metrics"><div className="metric-card"><span>Heures prévues</span><strong>{(department.plannedMinutes/60).toLocaleString('fr-FR',{maximumFractionDigits:1})} h</strong></div><div className="metric-card"><span>Heures faites</span><strong>{(department.actualMinutes/60).toLocaleString('fr-FR',{maximumFractionDigits:1})} h</strong></div><div className="metric-card"><span>Leçons prévues</span><strong>{department.lessonsPlannedPeriod}</strong></div><div className="metric-card"><span>Leçons terminées</span><strong>{department.lessonsDonePeriod}</strong></div></section><section className="card stats-progress"><ProgressBar label="Couverture horaire" value={department.hourlyCoverage}/><ProgressBar label="Couverture des programmes" value={department.programCoverage}/><ProgressBar label="Assiduité" value={department.attendance}/></section></>}
  <section className="card top-gap"><div className="section-title"><div><p className="eyebrow">Comparaison</p><h2>{canViewAll?'Par enseignant':'Mes indicateurs'}</h2></div></div><div className="schedule-table-wrap"><table className="data-table stats-table"><thead><tr><th>Enseignant</th><th>Prévu</th><th>Fait</th><th>Horaire</th><th>Programme</th><th>Assiduité</th><th>Leçons prév.</th><th>Leçons faites</th><th>Abs.</th></tr></thead><tbody>{rows.map(r=><tr key={r.teacherId}><td><strong>{r.teacherName}</strong></td><td>{(r.plannedMinutes/60).toLocaleString('fr-FR',{maximumFractionDigits:1})} h</td><td>{(r.actualMinutes/60).toLocaleString('fr-FR',{maximumFractionDigits:1})} h</td><td>{r.hourlyCoverage}%</td><td>{r.programCoverage}%</td><td>{r.attendance}%</td><td>{r.lessonsPlannedPeriod}</td><td>{r.lessonsDonePeriod}</td><td>{r.absences}</td></tr>)}{!rows.length&&<tr><td colSpan={9} className="empty-cell">Aucune donnée sur cette période.</td></tr>}</tbody></table></div></section>
  </AppShell>
}
