import AppShell from '@/components/AppShell'
import {requireMember,roleLabels} from '@/lib/auth/require-member'
import {shortTime} from '@/lib/date'

const weekdays=[['1','Lundi'],['2','Mardi'],['3','Mercredi'],['4','Jeudi'],['5','Vendredi'],['6','Samedi'],['7','Dimanche']]
export default async function TimetablePage(){
  const {supabase,profile,isManager,canViewAll}=await requireMember();const {data:year}=await supabase.from('school_years').select('id,name').eq('is_active',true).maybeSingle();let teacherId:string|undefined
  if(!canViewAll){const {data:t}=await supabase.from('teachers').select('id').eq('profile_id',profile.id).maybeSingle();teacherId=t?.id}
  let aq=supabase.from('teacher_assignments').select('id,teacher_id,teachers(profiles(full_name)),classes(name),subjects(name,code)').order('id');if(year)aq=aq.eq('school_year_id',year.id);if(teacherId)aq=aq.eq('teacher_id',teacherId);const {data:assignments}=await aq;const ids=(assignments??[]).map((a:any)=>a.id);const slots=ids.length?(await supabase.from('timetable_slots').select('id,assignment_id,weekday,start_time,end_time,room,effective_from,effective_to,active').in('assignment_id',ids).eq('active',true).order('weekday').order('start_time')).data??[]:[];const amap=new Map((assignments??[]).map((a:any)=>[a.id,a]))
  return <AppShell name={profile.full_name||'Collègue'} roleLabel={roleLabels[profile.role]} active="/timetable" isManager={isManager}><header className="page-header"><div><p className="eyebrow">Planification</p><h1>Emploi du temps</h1><p className="muted">{year?.name?`Année scolaire ${year.name}`:'Aucune année scolaire active'}</p></div>{isManager&&<a className="secondary-button" href="/admin/schedule">Modifier les affectations</a>}</header><section className="card"><div className="schedule-table-wrap"><table className="data-table"><thead><tr><th>Jour</th><th>Horaire</th><th>Enseignant</th><th>Classe</th><th>Matière</th><th>Salle</th></tr></thead><tbody>{slots.map((s:any)=>{const a:any=amap.get(s.assignment_id);return <tr key={s.id}><td>{weekdays.find(([v])=>Number(v)===s.weekday)?.[1]??s.weekday}</td><td><strong>{shortTime(s.start_time)}–{shortTime(s.end_time)}</strong></td><td>{a?.teachers?.profiles?.full_name||'—'}</td><td>{a?.classes?.name||'—'}</td><td>{a?.subjects?.name||'—'}</td><td>{s.room||'—'}</td></tr>})}{!slots.length&&<tr><td colSpan={6} className="empty-cell">Aucun créneau disponible.</td></tr>}</tbody></table></div></section></AppShell>
}
